### ISSUE TITLE
Required a complete SideNav Component

### ISSUE THREAD

**Issue by zetlify** [flavorly/vanilla-components#107]
Hi, 
Thanks for your efforts. Could we expect a complete Side Navbar with dropdown items, please?

If possible than you could also add a nice Top Navigation!

Thank you so much again.

**Comment by nikuscs** [comment]
I actually have done this for my apps with slideover + tailwindui, the reason why i didnt wanted to include this its because it really depends from project to project, a sidebar menu is often opinated, some projects for example i prefer to have a top navigation and so on. If you can point me exactly an example of what you are looking for i can probably send you a gist for it, regarding including it on the library im not sure if its a good ideia, convince me otherwise ? :p
