### ISSUE TITLE
Link in Datatable

### ISSUE THREAD

**Issue by juliancarstairs** [flavorly/vanilla-components#108]
Just wondering if it would be able to include a variation to the datatable, by allowing to insert a link within a particular chosen column? Happy to take a look but would need to be able to overwrite or change the datatable. I was thinking you can attach a kind of filter or use the transform function to insert the data manually. Or is there a slot that I can use and pass in a component or something of the sort? 

[https://vanilla-components.com/guide/integrations-datatables.html](url)

**Comment by nikuscs** [comment]
yes, columns have their own dynamic slots based on the key you gave while defining the schema/configuration. Hope thats what you were asking tor.

You can check more here : https://vanilla-components.com/guide/components/datatable.html#slot-dynamic-row-columnname

**Comment by juliancarstairs** [comment]
Hi @nikuscs thanks for your reply, I would rather have it defined in the php so I can auto populate the table dynamically. 
An example of what I mean, the record would have an Id column. the url would be test.com/posts/1 so on the datatable I would like to show a link to a link page for the Id, so you could click 1 and it would take you to a predefined url. Does that make sense?

**Comment by nikuscs** [comment]
It does make sense indeed, but we cannot render html from php directly into vue and make it dynamic, otherwise we would need something like Vue Runtime to proper do this or use v-html, keep in mind you are allowed to send objects from php, so your not limited to key value pairs. For what it matters and the end of the day in my opinion the render part should be always on vue side, so any logic to insert a link should be then passed to the vue side, laravel should only send raw data back and forward. Later today i can send some snippets on how i usually do this on my projects.

**Comment by juliancarstairs** [comment]
Used the following to get it to work with Inertia. But you are right in what you are saying, should be handled in the vue.

`<template
            #rowId="{ result }"
        >
            <Link :href="route('blog.show', {blog: result})">{{ result }}</Link>
        </template>`
