### ISSUE TITLE
Vue-tsc

### ISSUE THREAD

**Issue by jasminetracey** [flavorly/vanilla-components#114]
I have a project using [vue-tsc](https://www.npmjs.com/package/vue-tsc) when I try to use this package it throws a lot of type errors. 
Are there any plans on adding vue-tsc to the project to do type checking?

**Comment by nikuscs** [comment]
Hello @jasminetracey ! Thanks for your concern, there is indeed some types that needs to be taken care of, most of them are because the underlying implementation  of variants changed slightly. Our idiea for future is to move the variants system to tailwind-variants and also make sure all the types are infered via the new vue sfc.

So replying directly to your question, yes, they will be taken care of :p meanwhile if you qant have some fun, feel free to submit a PR.
